import NextTopLoader from "nextjs-toploader";
import "../globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader />
        <Toaster
          position="top-center"
          richColors
          closeButton={true}
          duration={4000}
        />
        {children}
      </body>
    </html>
  );
}
