import { authOptions } from "@/lib/authOptions";
import PushMockData from "@/components/PushMockData";
import { getDefaultParams } from "@/lib/actions/defaultParams.actions";
import { getServerSession } from "next-auth";
import Bus from "@/lib/database/models/bus";
import Generator from "@/lib/database/models/generator";

const mockData = [
  { busName: "PEE", nominalKV: 37 },
  { busName: "ZTM", nominalKV: 24 },
  { busName: "PTK", nominalKV: 36 },
  { busName: "CZW", nominalKV: 51 },
  { busName: "FSZ", nominalKV: 2 },
  { busName: "MMD", nominalKV: 23 },
  { busName: "HTV", nominalKV: 47 },
  { busName: "TLJ", nominalKV: 35 },
  { busName: "TSG", nominalKV: 37 },
  { busName: "FFU", nominalKV: 98 },
  { busName: "CHZ", nominalKV: 64 },
  { busName: "CHX", nominalKV: 100 },
  { busName: "AHC", nominalKV: 75 },
  { busName: "SVF", nominalKV: 51 },
  { busName: "MGV", nominalKV: 2 },
  { busName: "GIT", nominalKV: 81 },
  { busName: "FOS", nominalKV: 10 },
  { busName: "BJT", nominalKV: 22 },
  { busName: "ACC", nominalKV: 33 },
  { busName: "SJL", nominalKV: 83 },
  { busName: "PDM", nominalKV: 83 },
  { busName: "PNQ", nominalKV: 38 },
  { busName: "KWE", nominalKV: 2 },
  { busName: "TQN", nominalKV: 35 },
  { busName: "HUU", nominalKV: 44 },
  { busName: "POC", nominalKV: 86 },
  { busName: "OHB", nominalKV: 33 },
  { busName: "BIB", nominalKV: 20 },
  { busName: "SNW", nominalKV: 33 },
  { busName: "SOV", nominalKV: 28 },
  { busName: "HPE", nominalKV: 79 },
  { busName: "LNI", nominalKV: 91 },
  { busName: "SSU", nominalKV: 13 },
  { busName: "PZI", nominalKV: 54 },
  { busName: "FLO", nominalKV: 38 },
  { busName: "TKI", nominalKV: 88 },
  { busName: "BAV", nominalKV: 58 },
  { busName: "SWQ", nominalKV: 48 },
  { busName: "URO", nominalKV: 84 },
  { busName: "NLA", nominalKV: 17 },
  { busName: "LML", nominalKV: 62 },
  { busName: "LYM", nominalKV: 95 },
  { busName: "PDN", nominalKV: 97 },
  { busName: "ISU", nominalKV: 17 },
  { busName: "PNK", nominalKV: 40 },
  { busName: "JPA", nominalKV: 2 },
  { busName: "IRO", nominalKV: 11 },
  { busName: "THM", nominalKV: 47 },
  { busName: "TGD", nominalKV: 74 },
  { busName: "LBH", nominalKV: 89 },
  { busName: "LBC", nominalKV: 66 },
  { busName: "YQI", nominalKV: 26 },
  { busName: "FRR", nominalKV: 21 },
  { busName: "CSU", nominalKV: 57 },
  { busName: "VNS", nominalKV: 69 },
  { busName: "SYA", nominalKV: 96 },
  { busName: "HHE", nominalKV: 61 },
  { busName: "GRH", nominalKV: 37 },
  { busName: "OIC", nominalKV: 10 },
  { busName: "PDM", nominalKV: 19 },
  { busName: "KGY", nominalKV: 86 },
  { busName: "FKB", nominalKV: 2 },
  { busName: "COK", nominalKV: 4 },
  { busName: "NVI", nominalKV: 10 },
  { busName: "LUX", nominalKV: 47 },
  { busName: "MUW", nominalKV: 97 },
  { busName: "OEA", nominalKV: 74 },
  { busName: "GML", nominalKV: 65 },
  { busName: "DSM", nominalKV: 84 },
  { busName: "KKK", nominalKV: 77 },
  { busName: "PDA", nominalKV: 9 },
  { busName: "PDK", nominalKV: 18 },
  { busName: "NKG", nominalKV: 60 },
  { busName: "CYA", nominalKV: 18 },
  { busName: "KKY", nominalKV: 65 },
  { busName: "SZV", nominalKV: 86 },
  { busName: "WFI", nominalKV: 21 },
  { busName: "MWX", nominalKV: 24 },
  { busName: "LES", nominalKV: 85 },
  { busName: "AAJ", nominalKV: 17 },
  { busName: "WJF", nominalKV: 91 },
  { busName: "MUB", nominalKV: 44 },
  { busName: "JTI", nominalKV: 90 },
  { busName: "WLG", nominalKV: 43 },
  { busName: "SPP", nominalKV: 29 },
  { busName: "ETS", nominalKV: 40 },
  { busName: "0", nominalKV: 59 },
  { busName: "CKV", nominalKV: 87 },
  { busName: "KHH", nominalKV: 9 },
  { busName: "CNL", nominalKV: 17 },
  { busName: "IGE", nominalKV: 78 },
  { busName: "TAA", nominalKV: 99 },
  { busName: "GRO", nominalKV: 32 },
  { busName: "QNJ", nominalKV: 47 },
  { busName: "THN", nominalKV: 88 },
  { busName: "HMY", nominalKV: 88 },
  { busName: "SKJ", nominalKV: 87 },
  { busName: "BEW", nominalKV: 36 },
  { busName: "TAZ", nominalKV: 74 },
  { busName: "KDM", nominalKV: 49 },
  { busName: "TCD", nominalKV: 75 },
  { busName: "BSM", nominalKV: 43 },
  { busName: "KST", nominalKV: 63 },
  { busName: "HIF", nominalKV: 29 },
  { busName: "NVA", nominalKV: 66 },
  { busName: "AKY", nominalKV: 23 },
  { busName: "BOE", nominalKV: 53 },
  { busName: "ILR", nominalKV: 14 },
  { busName: "IVH", nominalKV: 89 },
  { busName: "BOT", nominalKV: 7 },
  { busName: "LPP", nominalKV: 100 },
  { busName: "CLG", nominalKV: 40 },
  { busName: "KTN", nominalKV: 68 },
  { busName: "EYP", nominalKV: 25 },
  { busName: "VGT", nominalKV: 73 },
  { busName: "YEV", nominalKV: 57 },
  { busName: "TEF", nominalKV: 54 },
  { busName: "CUP", nominalKV: 93 },
  { busName: "HOI", nominalKV: 34 },
  { busName: "RAH", nominalKV: 76 },
  { busName: "BZE", nominalKV: 78 },
  { busName: "GSJ", nominalKV: 12 },
  { busName: "UAC", nominalKV: 86 },
  { busName: "YEB", nominalKV: 11 },
  { busName: "CFF", nominalKV: 14 },
  { busName: "EHM", nominalKV: 46 },
  { busName: "ERT", nominalKV: 46 },
  { busName: "KKO", nominalKV: 32 },
  { busName: "PBF", nominalKV: 67 },
  { busName: "BBZ", nominalKV: 48 },
  { busName: "IXL", nominalKV: 60 },
  { busName: "WHD", nominalKV: 64 },
  { busName: "PLM", nominalKV: 16 },
  { busName: "IGE", nominalKV: 88 },
  { busName: "TSQ", nominalKV: 74 },
  { busName: "MTK", nominalKV: 84 },
  { busName: "HYS", nominalKV: 70 },
  { busName: "MPO", nominalKV: 10 },
  { busName: "SNX", nominalKV: 9 },
  { busName: "MLM", nominalKV: 75 },
  { busName: "TSH", nominalKV: 12 },
  { busName: "KOO", nominalKV: 59 },
  { busName: "SAR", nominalKV: 44 },
  { busName: "PUM", nominalKV: 33 },
  { busName: "DSM", nominalKV: 47 },
  { busName: "EVD", nominalKV: 14 },
  { busName: "YKQ", nominalKV: 36 },
  { busName: "WSD", nominalKV: 58 },
  { busName: "ULN", nominalKV: 88 },
  { busName: "KTO", nominalKV: 14 },
];

const page = async () => {
  const session = await getServerSession(authOptions);
  const { data: columns } = await getDefaultParams();
  const res = await Bus.insertMany(mockData);

  return (
    <PushMockData
      mockData={mockData}
      session={session}
      columns={columns[0].generatorColumns}
    />
  );
};

export default page;
