import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import PushMockData from "@/components/PushMockData";
import { getDefaultParams } from "@/lib/actions/defaultParams.actions";
import { getServerSession } from "next-auth";

const mockData = [
  {
    deviceName: "Jaguar",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "KPTI",
    busTo: "LUG",
    busSectionTo: "LSZA",
    positiveSequenceRohmsperunitlength: 63,
    positiveSequenceXohmsperunitlength: 74,
    positiveSequenceBseimensperunitlength: 60,
    negativeSequenceRohmsperunitlength: 94,
    negativeSequenceXohmsperunitlength: 30,
    negativeSequenceBseimensperunitlength: 73,
    lengthKm: 94,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Ukraine",
  },
  {
    deviceName: "Pontiac",
    type: "Over head conductor",
    busFrom: "Turquoise",
    busSectionFrom: "PCM",
    busTo: "UNU",
    busSectionTo: "KUNU",
    positiveSequenceRohmsperunitlength: 73,
    positiveSequenceXohmsperunitlength: 83,
    positiveSequenceBseimensperunitlength: 21,
    negativeSequenceRohmsperunitlength: 84,
    negativeSequenceXohmsperunitlength: 35,
    negativeSequenceBseimensperunitlength: 48,
    lengthKm: 89,
    lineReactorFrom: "Wood",
    lineReactorTo: "France",
  },
  {
    deviceName: "Dodge",
    type: "Cable",
    busFrom: "Orange",
    busSectionFrom: "EOCC",
    busTo: "BOK",
    busSectionTo: "KBOK",
    positiveSequenceRohmsperunitlength: 21,
    positiveSequenceXohmsperunitlength: 91,
    positiveSequenceBseimensperunitlength: 29,
    negativeSequenceRohmsperunitlength: 90,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 51,
    lengthKm: 37,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Mexico",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Maroon",
    busSectionFrom: "CHSCM",
    busTo: "IRZ",
    busSectionTo: "SWTP",
    positiveSequenceRohmsperunitlength: 92,
    positiveSequenceXohmsperunitlength: 39,
    positiveSequenceBseimensperunitlength: 79,
    negativeSequenceRohmsperunitlength: 13,
    negativeSequenceXohmsperunitlength: 91,
    negativeSequenceBseimensperunitlength: 78,
    lengthKm: 85,
    lineReactorFrom: "Steel",
    lineReactorTo: "China",
  },
  {
    deviceName: "Saab",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "TENX",
    busTo: "AQG",
    busSectionTo: "ZSAQ",
    positiveSequenceRohmsperunitlength: 89,
    positiveSequenceXohmsperunitlength: 87,
    positiveSequenceBseimensperunitlength: 33,
    negativeSequenceRohmsperunitlength: 25,
    negativeSequenceXohmsperunitlength: 45,
    negativeSequenceBseimensperunitlength: 34,
    lengthKm: 55,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Honda",
    type: "Cable",
    busFrom: "Teal",
    busSectionFrom: "SRC",
    busTo: "POC",
    busSectionTo: "KPOC",
    positiveSequenceRohmsperunitlength: 53,
    positiveSequenceXohmsperunitlength: 63,
    positiveSequenceBseimensperunitlength: 48,
    negativeSequenceRohmsperunitlength: 57,
    negativeSequenceXohmsperunitlength: 53,
    negativeSequenceBseimensperunitlength: 79,
    lengthKm: 98,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Kuwait",
  },
  {
    deviceName: "Maserati",
    type: "Cable",
    busFrom: "Maroon",
    busSectionFrom: "PBIB",
    busTo: "MKU",
    busSectionTo: "FOOK",
    positiveSequenceRohmsperunitlength: 66,
    positiveSequenceXohmsperunitlength: 6,
    positiveSequenceBseimensperunitlength: 96,
    negativeSequenceRohmsperunitlength: 85,
    negativeSequenceXohmsperunitlength: 94,
    negativeSequenceBseimensperunitlength: 49,
    lengthKm: 96,
    lineReactorFrom: "Stone",
    lineReactorTo: "China",
  },
  {
    deviceName: "Toyota",
    type: "Cable",
    busFrom: "Puce",
    busSectionFrom: "DYN^A",
    busTo: "HED",
    busSectionTo: "AK33",
    positiveSequenceRohmsperunitlength: 14,
    positiveSequenceXohmsperunitlength: 15,
    positiveSequenceBseimensperunitlength: 83,
    negativeSequenceRohmsperunitlength: 44,
    negativeSequenceXohmsperunitlength: 32,
    negativeSequenceBseimensperunitlength: 25,
    lengthKm: 67,
    lineReactorFrom: "Granite",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Nissan",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "BIDU",
    busTo: "SLE",
    busSectionTo: "KSLE",
    positiveSequenceRohmsperunitlength: 88,
    positiveSequenceXohmsperunitlength: 3,
    positiveSequenceBseimensperunitlength: 7,
    negativeSequenceRohmsperunitlength: 61,
    negativeSequenceXohmsperunitlength: 43,
    negativeSequenceBseimensperunitlength: 65,
    lengthKm: 56,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Honda",
    type: "Over head conductor",
    busFrom: "Puce",
    busSectionFrom: "STK",
    busTo: "LOT",
    busSectionTo: "KLOT",
    positiveSequenceRohmsperunitlength: 62,
    positiveSequenceXohmsperunitlength: 83,
    positiveSequenceBseimensperunitlength: 71,
    negativeSequenceRohmsperunitlength: 85,
    negativeSequenceXohmsperunitlength: 41,
    negativeSequenceBseimensperunitlength: 21,
    lengthKm: 32,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Porsche",
    type: "Over head conductor",
    busFrom: "Mauv",
    busSectionFrom: "MRK",
    busTo: "SNE",
    busSectionTo: "GVSN",
    positiveSequenceRohmsperunitlength: 31,
    positiveSequenceXohmsperunitlength: 44,
    positiveSequenceBseimensperunitlength: 67,
    negativeSequenceRohmsperunitlength: 79,
    negativeSequenceXohmsperunitlength: 91,
    negativeSequenceBseimensperunitlength: 92,
    lengthKm: 4,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Kia",
    type: "Over head conductor",
    busFrom: "Orange",
    busSectionFrom: "FIZZ",
    busTo: "SMW",
    busSectionTo: "GMMA",
    positiveSequenceRohmsperunitlength: 6,
    positiveSequenceXohmsperunitlength: 75,
    positiveSequenceBseimensperunitlength: 28,
    negativeSequenceRohmsperunitlength: 63,
    negativeSequenceXohmsperunitlength: 28,
    negativeSequenceBseimensperunitlength: 35,
    lengthKm: 98,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Japan",
  },
  {
    deviceName: "Ford",
    type: "Cable",
    busFrom: "Goldenrod",
    busSectionFrom: "HTHT",
    busTo: "0",
    busSectionTo: "SISP",
    positiveSequenceRohmsperunitlength: 7,
    positiveSequenceXohmsperunitlength: 25,
    positiveSequenceBseimensperunitlength: 70,
    negativeSequenceRohmsperunitlength: 38,
    negativeSequenceXohmsperunitlength: 90,
    negativeSequenceBseimensperunitlength: 29,
    lengthKm: 59,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "GMC",
    type: "Cable",
    busFrom: "Fuscia",
    busSectionFrom: "BVN",
    busTo: "AEA",
    busSectionTo: "NGTB",
    positiveSequenceRohmsperunitlength: 9,
    positiveSequenceXohmsperunitlength: 51,
    positiveSequenceBseimensperunitlength: 56,
    negativeSequenceRohmsperunitlength: 32,
    negativeSequenceXohmsperunitlength: 33,
    negativeSequenceBseimensperunitlength: 35,
    lengthKm: 53,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Vietnam",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Crimson",
    busSectionFrom: "GTS",
    busTo: "VAO",
    busSectionTo: "AGGV",
    positiveSequenceRohmsperunitlength: 98,
    positiveSequenceXohmsperunitlength: 95,
    positiveSequenceBseimensperunitlength: 97,
    negativeSequenceRohmsperunitlength: 10,
    negativeSequenceXohmsperunitlength: 53,
    negativeSequenceBseimensperunitlength: 36,
    lengthKm: 22,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Volvo",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "FALN",
    busTo: "HIA",
    busSectionTo: "ZSSH",
    positiveSequenceRohmsperunitlength: 17,
    positiveSequenceXohmsperunitlength: 76,
    positiveSequenceBseimensperunitlength: 74,
    negativeSequenceRohmsperunitlength: 77,
    negativeSequenceXohmsperunitlength: 33,
    negativeSequenceBseimensperunitlength: 39,
    lengthKm: 30,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Morocco",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "CCBG",
    busTo: "JTI",
    busSectionTo: "SWJW",
    positiveSequenceRohmsperunitlength: 78,
    positiveSequenceXohmsperunitlength: 12,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 75,
    negativeSequenceXohmsperunitlength: 50,
    negativeSequenceBseimensperunitlength: 24,
    lengthKm: 22,
    lineReactorFrom: "Glass",
    lineReactorTo: "Serbia",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Over head conductor",
    busFrom: "Fuscia",
    busSectionFrom: "CRME",
    busTo: "ISO",
    busSectionTo: "KISO",
    positiveSequenceRohmsperunitlength: 49,
    positiveSequenceXohmsperunitlength: 12,
    positiveSequenceBseimensperunitlength: 72,
    negativeSequenceRohmsperunitlength: 75,
    negativeSequenceXohmsperunitlength: 18,
    negativeSequenceBseimensperunitlength: 62,
    lengthKm: 64,
    lineReactorFrom: "Glass",
    lineReactorTo: "China",
  },
  {
    deviceName: "Acura",
    type: "Over head conductor",
    busFrom: "Mauv",
    busSectionFrom: "PLPC",
    busTo: "AYK",
    busSectionTo: "UAUR",
    positiveSequenceRohmsperunitlength: 95,
    positiveSequenceXohmsperunitlength: 53,
    positiveSequenceBseimensperunitlength: 70,
    negativeSequenceRohmsperunitlength: 22,
    negativeSequenceXohmsperunitlength: 83,
    negativeSequenceBseimensperunitlength: 36,
    lengthKm: 11,
    lineReactorFrom: "Stone",
    lineReactorTo: "United States",
  },
  {
    deviceName: "Bentley",
    type: "Cable",
    busFrom: "Violet",
    busSectionFrom: "HBNC",
    busTo: "WAG",
    busSectionTo: "NZWU",
    positiveSequenceRohmsperunitlength: 51,
    positiveSequenceXohmsperunitlength: 89,
    positiveSequenceBseimensperunitlength: 12,
    negativeSequenceRohmsperunitlength: 71,
    negativeSequenceXohmsperunitlength: 54,
    negativeSequenceBseimensperunitlength: 1,
    lengthKm: 13,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Guatemala",
  },
  {
    deviceName: "Mazda",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "HLX",
    busTo: "MHW",
    busSectionTo: "SLAG",
    positiveSequenceRohmsperunitlength: 35,
    positiveSequenceXohmsperunitlength: 83,
    positiveSequenceBseimensperunitlength: 67,
    negativeSequenceRohmsperunitlength: 82,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 80,
    lengthKm: 53,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Plymouth",
    type: "Over head conductor",
    busFrom: "Teal",
    busSectionFrom: "WB",
    busTo: "HFF",
    busSectionTo: "KHFF",
    positiveSequenceRohmsperunitlength: 36,
    positiveSequenceXohmsperunitlength: 21,
    positiveSequenceBseimensperunitlength: 49,
    negativeSequenceRohmsperunitlength: 34,
    negativeSequenceXohmsperunitlength: 41,
    negativeSequenceBseimensperunitlength: 99,
    lengthKm: 91,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Japan",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "JACK",
    busTo: "BZT",
    busSectionTo: "2TE0",
    positiveSequenceRohmsperunitlength: 25,
    positiveSequenceXohmsperunitlength: 20,
    positiveSequenceBseimensperunitlength: 76,
    negativeSequenceRohmsperunitlength: 76,
    negativeSequenceXohmsperunitlength: 63,
    negativeSequenceBseimensperunitlength: 92,
    lengthKm: 67,
    lineReactorFrom: "Brass",
    lineReactorTo: "France",
  },
  {
    deviceName: "GMC",
    type: "Cable",
    busFrom: "Green",
    busSectionFrom: "BL",
    busTo: "BDS",
    busSectionTo: "LIBR",
    positiveSequenceRohmsperunitlength: 37,
    positiveSequenceXohmsperunitlength: 44,
    positiveSequenceBseimensperunitlength: 81,
    negativeSequenceRohmsperunitlength: 12,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 13,
    lengthKm: 92,
    lineReactorFrom: "Brass",
    lineReactorTo: "Ecuador",
  },
  {
    deviceName: "Acura",
    type: "Cable",
    busFrom: "Pink",
    busSectionFrom: "ZIOP",
    busTo: "EWI",
    busSectionTo: "WABT",
    positiveSequenceRohmsperunitlength: 83,
    positiveSequenceXohmsperunitlength: 84,
    positiveSequenceBseimensperunitlength: 26,
    negativeSequenceRohmsperunitlength: 11,
    negativeSequenceXohmsperunitlength: 46,
    negativeSequenceBseimensperunitlength: 27,
    lengthKm: 52,
    lineReactorFrom: "Granite",
    lineReactorTo: "Vietnam",
  },
  {
    deviceName: "Plymouth",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "EVK",
    busTo: "PDM",
    busSectionTo: "MP00",
    positiveSequenceRohmsperunitlength: 61,
    positiveSequenceXohmsperunitlength: 90,
    positiveSequenceBseimensperunitlength: 30,
    negativeSequenceRohmsperunitlength: 80,
    negativeSequenceXohmsperunitlength: 93,
    negativeSequenceBseimensperunitlength: 19,
    lengthKm: 8,
    lineReactorFrom: "Rubber",
    lineReactorTo: "China",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Teal",
    busSectionFrom: "FLIC",
    busTo: "TXM",
    busSectionTo: "WAST",
    positiveSequenceRohmsperunitlength: 48,
    positiveSequenceXohmsperunitlength: 100,
    positiveSequenceBseimensperunitlength: 30,
    negativeSequenceRohmsperunitlength: 88,
    negativeSequenceXohmsperunitlength: 13,
    negativeSequenceBseimensperunitlength: 4,
    lengthKm: 57,
    lineReactorFrom: "Steel",
    lineReactorTo: "Kazakhstan",
  },
  {
    deviceName: "Lexus",
    type: "Cable",
    busFrom: "Green",
    busSectionFrom: "OZRK",
    busTo: "BDP",
    busSectionTo: "VNCG",
    positiveSequenceRohmsperunitlength: 87,
    positiveSequenceXohmsperunitlength: 33,
    positiveSequenceBseimensperunitlength: 71,
    negativeSequenceRohmsperunitlength: 8,
    negativeSequenceXohmsperunitlength: 36,
    negativeSequenceBseimensperunitlength: 57,
    lengthKm: 43,
    lineReactorFrom: "Glass",
    lineReactorTo: "Colombia",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Violet",
    busSectionFrom: "RIV",
    busTo: "WIL",
    busSectionTo: "HKNW",
    positiveSequenceRohmsperunitlength: 40,
    positiveSequenceXohmsperunitlength: 92,
    positiveSequenceBseimensperunitlength: 71,
    negativeSequenceRohmsperunitlength: 27,
    negativeSequenceXohmsperunitlength: 81,
    negativeSequenceBseimensperunitlength: 45,
    lengthKm: 22,
    lineReactorFrom: "Granite",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Pink",
    busSectionFrom: "PSET",
    busTo: "SAF",
    busSectionTo: "KSAF",
    positiveSequenceRohmsperunitlength: 40,
    positiveSequenceXohmsperunitlength: 78,
    positiveSequenceBseimensperunitlength: 25,
    negativeSequenceRohmsperunitlength: 65,
    negativeSequenceXohmsperunitlength: 71,
    negativeSequenceBseimensperunitlength: 88,
    lengthKm: 68,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Croatia",
  },
  {
    deviceName: "Lexus",
    type: "Cable",
    busFrom: "Fuscia",
    busSectionFrom: "KTCC",
    busTo: "LIB",
    busSectionTo: "YLIM",
    positiveSequenceRohmsperunitlength: 18,
    positiveSequenceXohmsperunitlength: 80,
    positiveSequenceBseimensperunitlength: 76,
    negativeSequenceRohmsperunitlength: 82,
    negativeSequenceXohmsperunitlength: 26,
    negativeSequenceBseimensperunitlength: 37,
    lengthKm: 82,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Kia",
    type: "Cable",
    busFrom: "Crimson",
    busSectionFrom: "TX",
    busTo: "MCG",
    busSectionTo: "PAMC",
    positiveSequenceRohmsperunitlength: 1,
    positiveSequenceXohmsperunitlength: 63,
    positiveSequenceBseimensperunitlength: 88,
    negativeSequenceRohmsperunitlength: 4,
    negativeSequenceXohmsperunitlength: 12,
    negativeSequenceBseimensperunitlength: 4,
    lengthKm: 41,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Brazil",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Green",
    busSectionFrom: "CLWT",
    busTo: "YWS",
    busSectionTo: "CAE5",
    positiveSequenceRohmsperunitlength: 23,
    positiveSequenceXohmsperunitlength: 8,
    positiveSequenceBseimensperunitlength: 36,
    negativeSequenceRohmsperunitlength: 24,
    negativeSequenceXohmsperunitlength: 91,
    negativeSequenceBseimensperunitlength: 76,
    lengthKm: 50,
    lineReactorFrom: "Stone",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Ford",
    type: "Cable",
    busFrom: "Fuscia",
    busSectionFrom: "SGF",
    busTo: "OME",
    busSectionTo: "PAOM",
    positiveSequenceRohmsperunitlength: 74,
    positiveSequenceXohmsperunitlength: 35,
    positiveSequenceBseimensperunitlength: 66,
    negativeSequenceRohmsperunitlength: 77,
    negativeSequenceXohmsperunitlength: 18,
    negativeSequenceBseimensperunitlength: 100,
    lengthKm: 94,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "France",
  },
  {
    deviceName: "Jeep",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "BONT",
    busTo: "GYI",
    busSectionTo: "HRYG",
    positiveSequenceRohmsperunitlength: 40,
    positiveSequenceXohmsperunitlength: 55,
    positiveSequenceBseimensperunitlength: 94,
    negativeSequenceRohmsperunitlength: 63,
    negativeSequenceXohmsperunitlength: 23,
    negativeSequenceBseimensperunitlength: 44,
    lengthKm: 79,
    lineReactorFrom: "Brass",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Audi",
    type: "Cable",
    busFrom: "Orange",
    busSectionFrom: "JRVR",
    busTo: "MNS",
    busSectionTo: "FLMA",
    positiveSequenceRohmsperunitlength: 40,
    positiveSequenceXohmsperunitlength: 78,
    positiveSequenceBseimensperunitlength: 26,
    negativeSequenceRohmsperunitlength: 94,
    negativeSequenceXohmsperunitlength: 59,
    negativeSequenceBseimensperunitlength: 71,
    lengthKm: 31,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Green",
    busSectionFrom: "NICE",
    busTo: "WMC",
    busSectionTo: "KWMC",
    positiveSequenceRohmsperunitlength: 34,
    positiveSequenceXohmsperunitlength: 84,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 35,
    negativeSequenceXohmsperunitlength: 44,
    negativeSequenceBseimensperunitlength: 41,
    lengthKm: 48,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Bolivia",
  },
  {
    deviceName: "Pontiac",
    type: "Cable",
    busFrom: "Aquamarine",
    busSectionFrom: "PNNT",
    busTo: "GVP",
    busSectionTo: "YGNV",
    positiveSequenceRohmsperunitlength: 8,
    positiveSequenceXohmsperunitlength: 97,
    positiveSequenceBseimensperunitlength: 1,
    negativeSequenceRohmsperunitlength: 42,
    negativeSequenceXohmsperunitlength: 48,
    negativeSequenceBseimensperunitlength: 94,
    lengthKm: 66,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Argentina",
  },
  {
    deviceName: "Infiniti",
    type: "Over head conductor",
    busFrom: "Crimson",
    busSectionFrom: "HQH",
    busTo: "ACZ",
    busSectionTo: "OIZB",
    positiveSequenceRohmsperunitlength: 85,
    positiveSequenceXohmsperunitlength: 52,
    positiveSequenceBseimensperunitlength: 49,
    negativeSequenceRohmsperunitlength: 48,
    negativeSequenceXohmsperunitlength: 33,
    negativeSequenceBseimensperunitlength: 47,
    lengthKm: 89,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Costa Rica",
  },
  {
    deviceName: "Hyundai",
    type: "Cable",
    busFrom: "Maroon",
    busSectionFrom: "DNR",
    busTo: "ACT",
    busSectionTo: "KACT",
    positiveSequenceRohmsperunitlength: 89,
    positiveSequenceXohmsperunitlength: 3,
    positiveSequenceBseimensperunitlength: 95,
    negativeSequenceRohmsperunitlength: 97,
    negativeSequenceXohmsperunitlength: 9,
    negativeSequenceBseimensperunitlength: 50,
    lengthKm: 15,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "South Africa",
  },
  {
    deviceName: "Lincoln",
    type: "Cable",
    busFrom: "Indigo",
    busSectionFrom: "OFC^L.CL",
    busTo: "GTO",
    busSectionTo: "WAMG",
    positiveSequenceRohmsperunitlength: 97,
    positiveSequenceXohmsperunitlength: 89,
    positiveSequenceBseimensperunitlength: 50,
    negativeSequenceRohmsperunitlength: 62,
    negativeSequenceXohmsperunitlength: 18,
    negativeSequenceBseimensperunitlength: 44,
    lengthKm: 34,
    lineReactorFrom: "Brass",
    lineReactorTo: "United States",
  },
  {
    deviceName: "Nissan",
    type: "Cable",
    busFrom: "Purple",
    busSectionFrom: "FMCIR",
    busTo: "TNV",
    busSectionTo: "PLFA",
    positiveSequenceRohmsperunitlength: 7,
    positiveSequenceXohmsperunitlength: 95,
    positiveSequenceBseimensperunitlength: 69,
    negativeSequenceRohmsperunitlength: 36,
    negativeSequenceXohmsperunitlength: 32,
    negativeSequenceBseimensperunitlength: 16,
    lengthKm: 44,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Slovenia",
  },
  {
    deviceName: "Aston Martin",
    type: "Cable",
    busFrom: "Goldenrod",
    busSectionFrom: "PSCT",
    busTo: "TKT",
    busSectionTo: "VTPT",
    positiveSequenceRohmsperunitlength: 74,
    positiveSequenceXohmsperunitlength: 88,
    positiveSequenceBseimensperunitlength: 14,
    negativeSequenceRohmsperunitlength: 6,
    negativeSequenceXohmsperunitlength: 43,
    negativeSequenceBseimensperunitlength: 43,
    lengthKm: 42,
    lineReactorFrom: "Stone",
    lineReactorTo: "China",
  },
  {
    deviceName: "Tesla",
    type: "Cable",
    busFrom: "Maroon",
    busSectionFrom: "VVV",
    busTo: "LTO",
    busSectionTo: "MMLT",
    positiveSequenceRohmsperunitlength: 86,
    positiveSequenceXohmsperunitlength: 81,
    positiveSequenceBseimensperunitlength: 80,
    negativeSequenceRohmsperunitlength: 11,
    negativeSequenceXohmsperunitlength: 38,
    negativeSequenceBseimensperunitlength: 13,
    lengthKm: 71,
    lineReactorFrom: "Steel",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Maserati",
    type: "Cable",
    busFrom: "Orange",
    busSectionFrom: "DCTH",
    busTo: "SQR",
    busSectionTo: "WAWS",
    positiveSequenceRohmsperunitlength: 18,
    positiveSequenceXohmsperunitlength: 28,
    positiveSequenceBseimensperunitlength: 18,
    negativeSequenceRohmsperunitlength: 72,
    negativeSequenceXohmsperunitlength: 51,
    negativeSequenceBseimensperunitlength: 50,
    lengthKm: 99,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Lexus",
    type: "Over head conductor",
    busFrom: "Pink",
    busSectionFrom: "WBKC",
    busTo: "ACH",
    busSectionTo: "LSZR",
    positiveSequenceRohmsperunitlength: 97,
    positiveSequenceXohmsperunitlength: 94,
    positiveSequenceBseimensperunitlength: 80,
    negativeSequenceRohmsperunitlength: 86,
    negativeSequenceXohmsperunitlength: 93,
    negativeSequenceBseimensperunitlength: 98,
    lengthKm: 7,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Azerbaijan",
  },
  {
    deviceName: "Mazda",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "LOGI",
    busTo: "HVK",
    busSectionTo: "BIHK",
    positiveSequenceRohmsperunitlength: 38,
    positiveSequenceXohmsperunitlength: 43,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 13,
    negativeSequenceXohmsperunitlength: 54,
    negativeSequenceBseimensperunitlength: 2,
    lengthKm: 48,
    lineReactorFrom: "Wood",
    lineReactorTo: "Colombia",
  },
  {
    deviceName: "Kia",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "PTR",
    busTo: "PTZ",
    busSectionTo: "SESM",
    positiveSequenceRohmsperunitlength: 88,
    positiveSequenceXohmsperunitlength: 97,
    positiveSequenceBseimensperunitlength: 99,
    negativeSequenceRohmsperunitlength: 55,
    negativeSequenceXohmsperunitlength: 22,
    negativeSequenceBseimensperunitlength: 91,
    lengthKm: 89,
    lineReactorFrom: "Glass",
    lineReactorTo: "Argentina",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Cable",
    busFrom: "Violet",
    busSectionFrom: "DJCO",
    busTo: "KOJ",
    busSectionTo: "RJFK",
    positiveSequenceRohmsperunitlength: 98,
    positiveSequenceXohmsperunitlength: 57,
    positiveSequenceBseimensperunitlength: 44,
    negativeSequenceRohmsperunitlength: 69,
    negativeSequenceXohmsperunitlength: 11,
    negativeSequenceBseimensperunitlength: 26,
    lengthKm: 11,
    lineReactorFrom: "Brass",
    lineReactorTo: "China",
  },
  {
    deviceName: "Infiniti",
    type: "Cable",
    busFrom: "Pink",
    busSectionFrom: "MCS",
    busTo: "GJT",
    busSectionTo: "KGJT",
    positiveSequenceRohmsperunitlength: 33,
    positiveSequenceXohmsperunitlength: 19,
    positiveSequenceBseimensperunitlength: 75,
    negativeSequenceRohmsperunitlength: 92,
    negativeSequenceXohmsperunitlength: 17,
    negativeSequenceBseimensperunitlength: 44,
    lengthKm: 92,
    lineReactorFrom: "Wood",
    lineReactorTo: "France",
  },
  {
    deviceName: "Honda",
    type: "Over head conductor",
    busFrom: "Blue",
    busSectionFrom: "WHLM",
    busTo: "ELA",
    busSectionTo: "KELA",
    positiveSequenceRohmsperunitlength: 44,
    positiveSequenceXohmsperunitlength: 33,
    positiveSequenceBseimensperunitlength: 55,
    negativeSequenceRohmsperunitlength: 32,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 69,
    lengthKm: 21,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Hyundai",
    type: "Cable",
    busFrom: "Crimson",
    busSectionFrom: "GDV",
    busTo: "EMT",
    busSectionTo: "KEMT",
    positiveSequenceRohmsperunitlength: 79,
    positiveSequenceXohmsperunitlength: 11,
    positiveSequenceBseimensperunitlength: 14,
    negativeSequenceRohmsperunitlength: 35,
    negativeSequenceXohmsperunitlength: 18,
    negativeSequenceBseimensperunitlength: 29,
    lengthKm: 33,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Bentley",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "NBTB",
    busTo: "MON",
    busSectionTo: "NZMC",
    positiveSequenceRohmsperunitlength: 69,
    positiveSequenceXohmsperunitlength: 67,
    positiveSequenceBseimensperunitlength: 94,
    negativeSequenceRohmsperunitlength: 99,
    negativeSequenceXohmsperunitlength: 36,
    negativeSequenceBseimensperunitlength: 23,
    lengthKm: 95,
    lineReactorFrom: "Steel",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Maybach",
    type: "Over head conductor",
    busFrom: "Teal",
    busSectionFrom: "DCO",
    busTo: "MQJ",
    busSectionTo: "UEMA",
    positiveSequenceRohmsperunitlength: 63,
    positiveSequenceXohmsperunitlength: 91,
    positiveSequenceBseimensperunitlength: 38,
    negativeSequenceRohmsperunitlength: 66,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 87,
    lengthKm: 34,
    lineReactorFrom: "Plastic",
    lineReactorTo: "China",
  },
  {
    deviceName: "Honda",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "BAS",
    busTo: "CGN",
    busSectionTo: "EDDK",
    positiveSequenceRohmsperunitlength: 83,
    positiveSequenceXohmsperunitlength: 69,
    positiveSequenceBseimensperunitlength: 25,
    negativeSequenceRohmsperunitlength: 37,
    negativeSequenceXohmsperunitlength: 90,
    negativeSequenceBseimensperunitlength: 64,
    lengthKm: 96,
    lineReactorFrom: "Brass",
    lineReactorTo: "Bulgaria",
  },
  {
    deviceName: "Acura",
    type: "Over head conductor",
    busFrom: "Fuscia",
    busSectionFrom: "FTEO",
    busTo: "BJE",
    positiveSequenceRohmsperunitlength: 63,
    positiveSequenceXohmsperunitlength: 27,
    positiveSequenceBseimensperunitlength: 3,
    negativeSequenceRohmsperunitlength: 34,
    negativeSequenceXohmsperunitlength: 64,
    negativeSequenceBseimensperunitlength: 25,
    lengthKm: 91,
    lineReactorFrom: "Wood",
    lineReactorTo: "Belgium",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Puce",
    busSectionFrom: "HOVNP",
    busTo: "MJI",
    busSectionTo: "HLLM",
    positiveSequenceRohmsperunitlength: 35,
    positiveSequenceXohmsperunitlength: 24,
    positiveSequenceBseimensperunitlength: 5,
    negativeSequenceRohmsperunitlength: 37,
    negativeSequenceXohmsperunitlength: 90,
    negativeSequenceBseimensperunitlength: 10,
    lengthKm: 15,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Holden",
    type: "Cable",
    busFrom: "Blue",
    busSectionFrom: "TDS",
    busTo: "YGR",
    busSectionTo: "CYGR",
    positiveSequenceRohmsperunitlength: 52,
    positiveSequenceXohmsperunitlength: 73,
    positiveSequenceBseimensperunitlength: 66,
    negativeSequenceRohmsperunitlength: 67,
    negativeSequenceXohmsperunitlength: 20,
    negativeSequenceBseimensperunitlength: 13,
    lengthKm: 1,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Moldova",
  },
  {
    deviceName: "Aston Martin",
    type: "Cable",
    busFrom: "Turquoise",
    busSectionFrom: "AVIR",
    busTo: "FLY",
    busSectionTo: "YFIL",
    positiveSequenceRohmsperunitlength: 76,
    positiveSequenceXohmsperunitlength: 47,
    positiveSequenceBseimensperunitlength: 74,
    negativeSequenceRohmsperunitlength: 47,
    negativeSequenceXohmsperunitlength: 14,
    negativeSequenceBseimensperunitlength: 3,
    lengthKm: 97,
    lineReactorFrom: "Rubber",
    lineReactorTo: "China",
  },
  {
    deviceName: "Eagle",
    type: "Cable",
    busFrom: "Puce",
    busSectionFrom: "PGR",
    busTo: "HGI",
    busSectionTo: "HSFA",
    positiveSequenceRohmsperunitlength: 88,
    positiveSequenceXohmsperunitlength: 51,
    positiveSequenceBseimensperunitlength: 48,
    negativeSequenceRohmsperunitlength: 3,
    negativeSequenceXohmsperunitlength: 13,
    negativeSequenceBseimensperunitlength: 4,
    lengthKm: 27,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Hyundai",
    type: "Cable",
    busFrom: "Purple",
    busSectionFrom: "TVE",
    busTo: "FNT",
    busSectionTo: "KFNT",
    positiveSequenceRohmsperunitlength: 20,
    positiveSequenceXohmsperunitlength: 74,
    positiveSequenceBseimensperunitlength: 97,
    negativeSequenceRohmsperunitlength: 2,
    negativeSequenceXohmsperunitlength: 85,
    negativeSequenceBseimensperunitlength: 21,
    lengthKm: 64,
    lineReactorFrom: "Stone",
    lineReactorTo: "Grenada",
  },
  {
    deviceName: "Toyota",
    type: "Cable",
    busFrom: "Teal",
    busSectionFrom: "SPCB",
    busTo: "OHB",
    busSectionTo: "FMFE",
    positiveSequenceRohmsperunitlength: 35,
    positiveSequenceXohmsperunitlength: 74,
    positiveSequenceBseimensperunitlength: 22,
    negativeSequenceRohmsperunitlength: 47,
    negativeSequenceXohmsperunitlength: 34,
    negativeSequenceBseimensperunitlength: 6,
    lengthKm: 93,
    lineReactorFrom: "Granite",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Nissan",
    type: "Cable",
    busFrom: "Turquoise",
    busSectionFrom: "TANH",
    busTo: "KRU",
    busSectionTo: "AYEA",
    positiveSequenceRohmsperunitlength: 54,
    positiveSequenceXohmsperunitlength: 12,
    positiveSequenceBseimensperunitlength: 84,
    negativeSequenceRohmsperunitlength: 30,
    negativeSequenceXohmsperunitlength: 87,
    negativeSequenceBseimensperunitlength: 35,
    lengthKm: 29,
    lineReactorFrom: "Wood",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Cadillac",
    type: "Over head conductor",
    busFrom: "Crimson",
    busSectionFrom: "NVRO",
    busTo: "WID",
    positiveSequenceRohmsperunitlength: 6,
    positiveSequenceXohmsperunitlength: 31,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 65,
    negativeSequenceXohmsperunitlength: 93,
    negativeSequenceBseimensperunitlength: 53,
    lengthKm: 99,
    lineReactorFrom: "Stone",
    lineReactorTo: "United States",
  },
  {
    deviceName: "Ford",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "MTL",
    busTo: "WFK",
    busSectionTo: "KFVE",
    positiveSequenceRohmsperunitlength: 55,
    positiveSequenceXohmsperunitlength: 80,
    positiveSequenceBseimensperunitlength: 64,
    negativeSequenceRohmsperunitlength: 37,
    negativeSequenceXohmsperunitlength: 66,
    negativeSequenceBseimensperunitlength: 59,
    lengthKm: 1,
    lineReactorFrom: "Steel",
    lineReactorTo: "China",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Red",
    busSectionFrom: "CNQ",
    busTo: "MHQ",
    busSectionTo: "EFMA",
    positiveSequenceRohmsperunitlength: 26,
    positiveSequenceXohmsperunitlength: 42,
    positiveSequenceBseimensperunitlength: 80,
    negativeSequenceRohmsperunitlength: 21,
    negativeSequenceXohmsperunitlength: 56,
    negativeSequenceBseimensperunitlength: 32,
    lengthKm: 26,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Aquamarine",
    busSectionFrom: "BPOPN",
    busTo: "IZA",
    busSectionTo: "SBZM",
    positiveSequenceRohmsperunitlength: 38,
    positiveSequenceXohmsperunitlength: 92,
    positiveSequenceBseimensperunitlength: 18,
    negativeSequenceRohmsperunitlength: 55,
    negativeSequenceXohmsperunitlength: 91,
    negativeSequenceBseimensperunitlength: 36,
    lengthKm: 53,
    lineReactorFrom: "Wood",
    lineReactorTo: "China",
  },
  {
    deviceName: "Ford",
    type: "Cable",
    busFrom: "Indigo",
    busSectionFrom: "CRR",
    busTo: "TIW",
    busSectionTo: "KTIW",
    positiveSequenceRohmsperunitlength: 100,
    positiveSequenceXohmsperunitlength: 11,
    positiveSequenceBseimensperunitlength: 25,
    negativeSequenceRohmsperunitlength: 32,
    negativeSequenceXohmsperunitlength: 76,
    negativeSequenceBseimensperunitlength: 58,
    lengthKm: 11,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "DATA",
    busTo: "FMN",
    busSectionTo: "KFMN",
    positiveSequenceRohmsperunitlength: 89,
    positiveSequenceXohmsperunitlength: 98,
    positiveSequenceBseimensperunitlength: 19,
    negativeSequenceRohmsperunitlength: 60,
    negativeSequenceXohmsperunitlength: 80,
    negativeSequenceBseimensperunitlength: 39,
    lengthKm: 43,
    lineReactorFrom: "Stone",
    lineReactorTo: "Macedonia",
  },
  {
    deviceName: "Porsche",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "KIN",
    busTo: "GOR",
    busSectionTo: "HAGR",
    positiveSequenceRohmsperunitlength: 35,
    positiveSequenceXohmsperunitlength: 62,
    positiveSequenceBseimensperunitlength: 88,
    negativeSequenceRohmsperunitlength: 20,
    negativeSequenceXohmsperunitlength: 93,
    negativeSequenceBseimensperunitlength: 71,
    lengthKm: 45,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Volkswagen",
    type: "Cable",
    busFrom: "Turquoise",
    busSectionFrom: "FT",
    busTo: "TLO",
    busSectionTo: "AYXO",
    positiveSequenceRohmsperunitlength: 73,
    positiveSequenceXohmsperunitlength: 55,
    positiveSequenceBseimensperunitlength: 22,
    negativeSequenceRohmsperunitlength: 100,
    negativeSequenceXohmsperunitlength: 62,
    negativeSequenceBseimensperunitlength: 40,
    lengthKm: 48,
    lineReactorFrom: "Glass",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "MINI",
    type: "Over head conductor",
    busFrom: "Turquoise",
    busSectionFrom: "AMG",
    busTo: "ZNZ",
    busSectionTo: "HTZA",
    positiveSequenceRohmsperunitlength: 58,
    positiveSequenceXohmsperunitlength: 8,
    positiveSequenceBseimensperunitlength: 75,
    negativeSequenceRohmsperunitlength: 62,
    negativeSequenceXohmsperunitlength: 12,
    negativeSequenceBseimensperunitlength: 89,
    lengthKm: 26,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Jaguar",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "ACRX",
    busTo: "NHD",
    busSectionTo: "OMDM",
    positiveSequenceRohmsperunitlength: 66,
    positiveSequenceXohmsperunitlength: 13,
    positiveSequenceBseimensperunitlength: 80,
    negativeSequenceRohmsperunitlength: 49,
    negativeSequenceXohmsperunitlength: 91,
    negativeSequenceBseimensperunitlength: 75,
    lengthKm: 68,
    lineReactorFrom: "Glass",
    lineReactorTo: "Argentina",
  },
  {
    deviceName: "Ford",
    type: "Cable",
    busFrom: "Teal",
    busSectionFrom: "FN",
    busTo: "DSK",
    busSectionTo: "OPDI",
    positiveSequenceRohmsperunitlength: 57,
    positiveSequenceXohmsperunitlength: 76,
    positiveSequenceBseimensperunitlength: 72,
    negativeSequenceRohmsperunitlength: 35,
    negativeSequenceXohmsperunitlength: 86,
    negativeSequenceBseimensperunitlength: 84,
    lengthKm: 67,
    lineReactorFrom: "Glass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "VTWV",
    busTo: "PMK",
    busSectionTo: "YPAM",
    positiveSequenceRohmsperunitlength: 80,
    positiveSequenceXohmsperunitlength: 19,
    positiveSequenceBseimensperunitlength: 96,
    negativeSequenceRohmsperunitlength: 21,
    negativeSequenceXohmsperunitlength: 37,
    negativeSequenceBseimensperunitlength: 87,
    lengthKm: 50,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "China",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Crimson",
    busSectionFrom: "GXP^B",
    busTo: "MGG",
    positiveSequenceRohmsperunitlength: 34,
    positiveSequenceXohmsperunitlength: 88,
    positiveSequenceBseimensperunitlength: 96,
    negativeSequenceRohmsperunitlength: 81,
    negativeSequenceXohmsperunitlength: 19,
    negativeSequenceBseimensperunitlength: 84,
    lengthKm: 13,
    lineReactorFrom: "Steel",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Pontiac",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "UBSI",
    busTo: "MNU",
    busSectionTo: "VYMM",
    positiveSequenceRohmsperunitlength: 16,
    positiveSequenceXohmsperunitlength: 19,
    positiveSequenceBseimensperunitlength: 34,
    negativeSequenceRohmsperunitlength: 93,
    negativeSequenceXohmsperunitlength: 73,
    negativeSequenceBseimensperunitlength: 31,
    lengthKm: 15,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "BMW",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "SCMP",
    busTo: "HYC",
    busSectionTo: "EGTB",
    positiveSequenceRohmsperunitlength: 61,
    positiveSequenceXohmsperunitlength: 83,
    positiveSequenceBseimensperunitlength: 18,
    negativeSequenceRohmsperunitlength: 72,
    negativeSequenceXohmsperunitlength: 75,
    negativeSequenceBseimensperunitlength: 92,
    lengthKm: 11,
    lineReactorFrom: "Wood",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Maroon",
    busSectionFrom: "COT",
    busTo: "ORH",
    busSectionTo: "KORH",
    positiveSequenceRohmsperunitlength: 36,
    positiveSequenceXohmsperunitlength: 57,
    positiveSequenceBseimensperunitlength: 53,
    negativeSequenceRohmsperunitlength: 71,
    negativeSequenceXohmsperunitlength: 39,
    negativeSequenceBseimensperunitlength: 40,
    lengthKm: 41,
    lineReactorFrom: "Glass",
    lineReactorTo: "Thailand",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Khaki",
    busSectionFrom: "SINO",
    busTo: "LXU",
    busSectionTo: "FLLK",
    positiveSequenceRohmsperunitlength: 71,
    positiveSequenceXohmsperunitlength: 48,
    positiveSequenceBseimensperunitlength: 38,
    negativeSequenceRohmsperunitlength: 51,
    negativeSequenceXohmsperunitlength: 69,
    negativeSequenceBseimensperunitlength: 31,
    lengthKm: 53,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "BMW",
    type: "Over head conductor",
    busFrom: "Crimson",
    busSectionFrom: "KGJI",
    busTo: "YDP",
    busSectionTo: "CYDP",
    positiveSequenceRohmsperunitlength: 91,
    positiveSequenceXohmsperunitlength: 88,
    positiveSequenceBseimensperunitlength: 61,
    negativeSequenceRohmsperunitlength: 11,
    negativeSequenceXohmsperunitlength: 42,
    negativeSequenceBseimensperunitlength: 86,
    lengthKm: 15,
    lineReactorFrom: "Glass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Mauv",
    busSectionFrom: "ECL",
    busTo: "CNE",
    busSectionTo: "1V6",
    positiveSequenceRohmsperunitlength: 41,
    positiveSequenceXohmsperunitlength: 64,
    positiveSequenceBseimensperunitlength: 37,
    negativeSequenceRohmsperunitlength: 87,
    negativeSequenceXohmsperunitlength: 65,
    negativeSequenceBseimensperunitlength: 79,
    lengthKm: 85,
    lineReactorFrom: "Granite",
    lineReactorTo: "Tanzania",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Blue",
    busSectionFrom: "EVEP",
    busTo: "DCY",
    busSectionTo: "ZUDC",
    positiveSequenceRohmsperunitlength: 34,
    positiveSequenceXohmsperunitlength: 41,
    positiveSequenceBseimensperunitlength: 63,
    negativeSequenceRohmsperunitlength: 36,
    negativeSequenceXohmsperunitlength: 38,
    negativeSequenceBseimensperunitlength: 67,
    lengthKm: 31,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Mitsubishi",
    type: "Over head conductor",
    busFrom: "Indigo",
    busSectionFrom: "VXUS",
    busTo: "HIB",
    busSectionTo: "KHIB",
    positiveSequenceRohmsperunitlength: 25,
    positiveSequenceXohmsperunitlength: 75,
    positiveSequenceBseimensperunitlength: 48,
    negativeSequenceRohmsperunitlength: 80,
    negativeSequenceXohmsperunitlength: 8,
    negativeSequenceBseimensperunitlength: 53,
    lengthKm: 90,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Lincoln",
    type: "Over head conductor",
    busFrom: "Turquoise",
    busSectionFrom: "LEN",
    busTo: "KCB",
    busSectionTo: "SMTP",
    positiveSequenceRohmsperunitlength: 78,
    positiveSequenceXohmsperunitlength: 98,
    positiveSequenceBseimensperunitlength: 35,
    negativeSequenceRohmsperunitlength: 16,
    negativeSequenceXohmsperunitlength: 81,
    negativeSequenceBseimensperunitlength: 92,
    lengthKm: 70,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Red",
    busSectionFrom: "CECE",
    busTo: "SXM",
    busSectionTo: "TNCM",
    positiveSequenceRohmsperunitlength: 77,
    positiveSequenceXohmsperunitlength: 96,
    positiveSequenceBseimensperunitlength: 64,
    negativeSequenceRohmsperunitlength: 3,
    negativeSequenceXohmsperunitlength: 38,
    negativeSequenceBseimensperunitlength: 48,
    lengthKm: 60,
    lineReactorFrom: "Brass",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Aston Martin",
    type: "Cable",
    busFrom: "Fuscia",
    busSectionFrom: "MRUS",
    busTo: "LKV",
    busSectionTo: "KLKV",
    positiveSequenceRohmsperunitlength: 92,
    positiveSequenceXohmsperunitlength: 7,
    positiveSequenceBseimensperunitlength: 18,
    negativeSequenceRohmsperunitlength: 81,
    negativeSequenceXohmsperunitlength: 77,
    negativeSequenceBseimensperunitlength: 4,
    lengthKm: 26,
    lineReactorFrom: "Steel",
    lineReactorTo: "Japan",
  },
  {
    deviceName: "Mitsubishi",
    type: "Cable",
    busFrom: "Aquamarine",
    busSectionFrom: "TKF",
    busTo: "GVX",
    busSectionTo: "ESSK",
    positiveSequenceRohmsperunitlength: 85,
    positiveSequenceXohmsperunitlength: 77,
    positiveSequenceBseimensperunitlength: 3,
    negativeSequenceRohmsperunitlength: 74,
    negativeSequenceXohmsperunitlength: 72,
    negativeSequenceBseimensperunitlength: 75,
    lengthKm: 13,
    lineReactorFrom: "Wood",
    lineReactorTo: "Bangladesh",
  },
  {
    deviceName: "Pontiac",
    type: "Cable",
    busFrom: "Puce",
    busSectionFrom: "UTF",
    busTo: "MWB",
    busSectionTo: "YMRW",
    positiveSequenceRohmsperunitlength: 46,
    positiveSequenceXohmsperunitlength: 58,
    positiveSequenceBseimensperunitlength: 79,
    negativeSequenceRohmsperunitlength: 71,
    negativeSequenceXohmsperunitlength: 27,
    negativeSequenceBseimensperunitlength: 68,
    lengthKm: 97,
    lineReactorFrom: "Granite",
    lineReactorTo: "Mongolia",
  },
  {
    deviceName: "Isuzu",
    type: "Cable",
    busFrom: "Purple",
    busSectionFrom: "SHOP",
    busTo: "JDP",
    busSectionTo: "LFPI",
    positiveSequenceRohmsperunitlength: 47,
    positiveSequenceXohmsperunitlength: 20,
    positiveSequenceBseimensperunitlength: 36,
    negativeSequenceRohmsperunitlength: 100,
    negativeSequenceXohmsperunitlength: 13,
    negativeSequenceBseimensperunitlength: 54,
    lengthKm: 82,
    lineReactorFrom: "Steel",
    lineReactorTo: "United States",
  },
  {
    deviceName: "Cadillac",
    type: "Cable",
    busFrom: "Orange",
    busSectionFrom: "GLA",
    busTo: "FLR",
    busSectionTo: "LIRQ",
    positiveSequenceRohmsperunitlength: 14,
    positiveSequenceXohmsperunitlength: 76,
    positiveSequenceBseimensperunitlength: 68,
    negativeSequenceRohmsperunitlength: 16,
    negativeSequenceXohmsperunitlength: 71,
    negativeSequenceBseimensperunitlength: 31,
    lengthKm: 15,
    lineReactorFrom: "Steel",
    lineReactorTo: "Somalia",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "ABCO",
    busTo: "LCI",
    busSectionTo: "KLCI",
    positiveSequenceRohmsperunitlength: 51,
    positiveSequenceXohmsperunitlength: 84,
    positiveSequenceBseimensperunitlength: 65,
    negativeSequenceRohmsperunitlength: 12,
    negativeSequenceXohmsperunitlength: 50,
    negativeSequenceBseimensperunitlength: 96,
    lengthKm: 81,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Orange",
    busSectionFrom: "RES",
    busTo: "CET",
    busSectionTo: "LFOU",
    positiveSequenceRohmsperunitlength: 38,
    positiveSequenceXohmsperunitlength: 27,
    positiveSequenceBseimensperunitlength: 34,
    negativeSequenceRohmsperunitlength: 84,
    negativeSequenceXohmsperunitlength: 4,
    negativeSequenceBseimensperunitlength: 19,
    lengthKm: 32,
    lineReactorFrom: "Brass",
    lineReactorTo: "Palestinian Territory",
  },
  {
    deviceName: "Land Rover",
    type: "Over head conductor",
    busFrom: "Violet",
    busSectionFrom: "PEZ",
    busTo: "SVS",
    busSectionTo: "SVS",
    positiveSequenceRohmsperunitlength: 9,
    positiveSequenceXohmsperunitlength: 87,
    positiveSequenceBseimensperunitlength: 73,
    negativeSequenceRohmsperunitlength: 4,
    negativeSequenceXohmsperunitlength: 98,
    negativeSequenceBseimensperunitlength: 33,
    lengthKm: 36,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Toyota",
    type: "Cable",
    busFrom: "Aquamarine",
    busSectionFrom: "ESES",
    busTo: "RCY",
    busSectionTo: "MYRP",
    positiveSequenceRohmsperunitlength: 23,
    positiveSequenceXohmsperunitlength: 21,
    positiveSequenceBseimensperunitlength: 70,
    negativeSequenceRohmsperunitlength: 32,
    negativeSequenceXohmsperunitlength: 59,
    negativeSequenceBseimensperunitlength: 50,
    lengthKm: 100,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Vietnam",
  },
  {
    deviceName: "Mitsubishi",
    type: "Cable",
    busFrom: "Mauv",
    busSectionFrom: "PEI^B",
    busTo: "AMH",
    busSectionTo: "HAAM",
    positiveSequenceRohmsperunitlength: 3,
    positiveSequenceXohmsperunitlength: 28,
    positiveSequenceBseimensperunitlength: 62,
    negativeSequenceRohmsperunitlength: 30,
    negativeSequenceXohmsperunitlength: 71,
    negativeSequenceBseimensperunitlength: 41,
    lengthKm: 84,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Argentina",
  },
  {
    deviceName: "Lincoln",
    type: "Cable",
    busFrom: "Indigo",
    busSectionFrom: "AXAR",
    busTo: "QUY",
    busSectionTo: "EGUY",
    positiveSequenceRohmsperunitlength: 6,
    positiveSequenceXohmsperunitlength: 3,
    positiveSequenceBseimensperunitlength: 19,
    negativeSequenceRohmsperunitlength: 67,
    negativeSequenceXohmsperunitlength: 94,
    negativeSequenceBseimensperunitlength: 25,
    lengthKm: 3,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Japan",
  },
  {
    deviceName: "GMC",
    type: "Cable",
    busFrom: "Goldenrod",
    busSectionFrom: "ASB^D",
    busTo: "AMC",
    busSectionTo: "FTTN",
    positiveSequenceRohmsperunitlength: 3,
    positiveSequenceXohmsperunitlength: 81,
    positiveSequenceBseimensperunitlength: 43,
    negativeSequenceRohmsperunitlength: 13,
    negativeSequenceXohmsperunitlength: 75,
    negativeSequenceBseimensperunitlength: 89,
    lengthKm: 65,
    lineReactorFrom: "Brass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Volvo",
    type: "Cable",
    busFrom: "Pink",
    busSectionFrom: "DRQ",
    busTo: "CBF",
    busSectionTo: "KCBF",
    positiveSequenceRohmsperunitlength: 9,
    positiveSequenceXohmsperunitlength: 84,
    positiveSequenceBseimensperunitlength: 80,
    negativeSequenceRohmsperunitlength: 9,
    negativeSequenceXohmsperunitlength: 71,
    negativeSequenceBseimensperunitlength: 54,
    lengthKm: 62,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Colombia",
  },
  {
    deviceName: "Lexus",
    type: "Over head conductor",
    busFrom: "Maroon",
    busSectionFrom: "CALL",
    busTo: "KXK",
    busSectionTo: "UHKK",
    positiveSequenceRohmsperunitlength: 49,
    positiveSequenceXohmsperunitlength: 26,
    positiveSequenceBseimensperunitlength: 73,
    negativeSequenceRohmsperunitlength: 64,
    negativeSequenceXohmsperunitlength: 4,
    negativeSequenceBseimensperunitlength: 70,
    lengthKm: 32,
    lineReactorFrom: "Brass",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Land Rover",
    type: "Over head conductor",
    busFrom: "Aquamarine",
    busSectionFrom: "CRDS",
    busTo: "MEK",
    busSectionTo: "GMFM",
    positiveSequenceRohmsperunitlength: 69,
    positiveSequenceXohmsperunitlength: 100,
    positiveSequenceBseimensperunitlength: 71,
    negativeSequenceRohmsperunitlength: 11,
    negativeSequenceXohmsperunitlength: 88,
    negativeSequenceBseimensperunitlength: 36,
    lengthKm: 75,
    lineReactorFrom: "Glass",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Audi",
    type: "Over head conductor",
    busFrom: "Blue",
    busSectionFrom: "JTPY",
    busTo: "QPD",
    busSectionTo: "MUPR",
    positiveSequenceRohmsperunitlength: 100,
    positiveSequenceXohmsperunitlength: 32,
    positiveSequenceBseimensperunitlength: 82,
    negativeSequenceRohmsperunitlength: 62,
    negativeSequenceXohmsperunitlength: 37,
    negativeSequenceBseimensperunitlength: 83,
    lengthKm: 22,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Estonia",
  },
  {
    deviceName: "Acura",
    type: "Over head conductor",
    busFrom: "Green",
    busSectionFrom: "SBOW",
    busTo: "TBS",
    busSectionTo: "UGTB",
    positiveSequenceRohmsperunitlength: 73,
    positiveSequenceXohmsperunitlength: 53,
    positiveSequenceBseimensperunitlength: 24,
    negativeSequenceRohmsperunitlength: 5,
    negativeSequenceXohmsperunitlength: 77,
    negativeSequenceBseimensperunitlength: 8,
    lengthKm: 95,
    lineReactorFrom: "Granite",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "BMW",
    type: "Cable",
    busFrom: "Khaki",
    busSectionFrom: "ROSEU",
    busTo: "JIB",
    busSectionTo: "HDAM",
    positiveSequenceRohmsperunitlength: 67,
    positiveSequenceXohmsperunitlength: 59,
    positiveSequenceBseimensperunitlength: 41,
    negativeSequenceRohmsperunitlength: 40,
    negativeSequenceXohmsperunitlength: 30,
    negativeSequenceBseimensperunitlength: 89,
    lengthKm: 79,
    lineReactorFrom: "Steel",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Buick",
    type: "Over head conductor",
    busFrom: "Turquoise",
    busSectionFrom: "TMK^C",
    busTo: "PNH",
    busSectionTo: "VDPP",
    positiveSequenceRohmsperunitlength: 83,
    positiveSequenceXohmsperunitlength: 2,
    positiveSequenceBseimensperunitlength: 5,
    negativeSequenceRohmsperunitlength: 32,
    negativeSequenceXohmsperunitlength: 68,
    negativeSequenceBseimensperunitlength: 56,
    lengthKm: 94,
    lineReactorFrom: "Steel",
    lineReactorTo: "Oman",
  },
  {
    deviceName: "Porsche",
    type: "Over head conductor",
    busFrom: "Khaki",
    busSectionFrom: "ARC",
    busTo: "URE",
    busSectionTo: "EEKE",
    positiveSequenceRohmsperunitlength: 60,
    positiveSequenceXohmsperunitlength: 6,
    positiveSequenceBseimensperunitlength: 21,
    negativeSequenceRohmsperunitlength: 95,
    negativeSequenceXohmsperunitlength: 32,
    negativeSequenceBseimensperunitlength: 22,
    lengthKm: 41,
    lineReactorFrom: "Brass",
    lineReactorTo: "France",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "BCS",
    busTo: "UTC",
    busSectionTo: "EHSB",
    positiveSequenceRohmsperunitlength: 91,
    positiveSequenceXohmsperunitlength: 93,
    positiveSequenceBseimensperunitlength: 79,
    negativeSequenceRohmsperunitlength: 55,
    negativeSequenceXohmsperunitlength: 77,
    negativeSequenceBseimensperunitlength: 65,
    lengthKm: 30,
    lineReactorFrom: "Stone",
    lineReactorTo: "China",
  },
  {
    deviceName: "Audi",
    type: "Over head conductor",
    busFrom: "Fuscia",
    busSectionFrom: "ITUS",
    busTo: "CHN",
    busSectionTo: "RKJU",
    positiveSequenceRohmsperunitlength: 26,
    positiveSequenceXohmsperunitlength: 38,
    positiveSequenceBseimensperunitlength: 46,
    negativeSequenceRohmsperunitlength: 49,
    negativeSequenceXohmsperunitlength: 19,
    negativeSequenceBseimensperunitlength: 36,
    lengthKm: 51,
    lineReactorFrom: "Granite",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Lamborghini",
    type: "Cable",
    busFrom: "Maroon",
    busSectionFrom: "JTD",
    busTo: "DPO",
    busSectionTo: "YDPO",
    positiveSequenceRohmsperunitlength: 16,
    positiveSequenceXohmsperunitlength: 74,
    positiveSequenceBseimensperunitlength: 44,
    negativeSequenceRohmsperunitlength: 75,
    negativeSequenceXohmsperunitlength: 30,
    negativeSequenceBseimensperunitlength: 31,
    lengthKm: 100,
    lineReactorFrom: "Steel",
    lineReactorTo: "China",
  },
  {
    deviceName: "Mazda",
    type: "Over head conductor",
    busFrom: "Red",
    busSectionFrom: "HTBI",
    busTo: "GRK",
    busSectionTo: "KGRK",
    positiveSequenceRohmsperunitlength: 39,
    positiveSequenceXohmsperunitlength: 31,
    positiveSequenceBseimensperunitlength: 30,
    negativeSequenceRohmsperunitlength: 91,
    negativeSequenceXohmsperunitlength: 55,
    negativeSequenceBseimensperunitlength: 23,
    lengthKm: 73,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Crimson",
    busSectionFrom: "VEON",
    busTo: "GHT",
    busSectionTo: "HLGT",
    positiveSequenceRohmsperunitlength: 51,
    positiveSequenceXohmsperunitlength: 74,
    positiveSequenceBseimensperunitlength: 1,
    negativeSequenceRohmsperunitlength: 78,
    negativeSequenceXohmsperunitlength: 70,
    negativeSequenceBseimensperunitlength: 72,
    lengthKm: 9,
    lineReactorFrom: "Wood",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "MINI",
    type: "Over head conductor",
    busFrom: "Crimson",
    busSectionFrom: "JONE",
    busTo: "MPT",
    busSectionTo: "WPMN",
    positiveSequenceRohmsperunitlength: 10,
    positiveSequenceXohmsperunitlength: 71,
    positiveSequenceBseimensperunitlength: 83,
    negativeSequenceRohmsperunitlength: 17,
    negativeSequenceXohmsperunitlength: 87,
    negativeSequenceBseimensperunitlength: 41,
    lengthKm: 63,
    lineReactorFrom: "Glass",
    lineReactorTo: "Dominican Republic",
  },
  {
    deviceName: "Mercury",
    type: "Cable",
    busFrom: "Maroon",
    busSectionFrom: "MKSI",
    busTo: "LMI",
    busSectionTo: "AYLU",
    positiveSequenceRohmsperunitlength: 95,
    positiveSequenceXohmsperunitlength: 87,
    positiveSequenceBseimensperunitlength: 78,
    negativeSequenceRohmsperunitlength: 26,
    negativeSequenceXohmsperunitlength: 16,
    negativeSequenceBseimensperunitlength: 72,
    lengthKm: 57,
    lineReactorFrom: "Wood",
    lineReactorTo: "Norway",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "TM",
    busTo: "GEO",
    busSectionTo: "SYCJ",
    positiveSequenceRohmsperunitlength: 17,
    positiveSequenceXohmsperunitlength: 23,
    positiveSequenceBseimensperunitlength: 99,
    negativeSequenceRohmsperunitlength: 91,
    negativeSequenceXohmsperunitlength: 65,
    negativeSequenceBseimensperunitlength: 56,
    lengthKm: 79,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Nigeria",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Over head conductor",
    busFrom: "Aquamarine",
    busSectionFrom: "ABMD",
    busTo: "SIT",
    busSectionTo: "PASI",
    positiveSequenceRohmsperunitlength: 67,
    positiveSequenceXohmsperunitlength: 46,
    positiveSequenceBseimensperunitlength: 55,
    negativeSequenceRohmsperunitlength: 81,
    negativeSequenceXohmsperunitlength: 35,
    negativeSequenceBseimensperunitlength: 45,
    lengthKm: 23,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Toyota",
    type: "Cable",
    busFrom: "Purple",
    busSectionFrom: "CHCT",
    busTo: "YGE",
    positiveSequenceRohmsperunitlength: 7,
    positiveSequenceXohmsperunitlength: 5,
    positiveSequenceBseimensperunitlength: 24,
    negativeSequenceRohmsperunitlength: 81,
    negativeSequenceXohmsperunitlength: 70,
    negativeSequenceBseimensperunitlength: 1,
    lengthKm: 44,
    lineReactorFrom: "Brass",
    lineReactorTo: "Italy",
  },
  {
    deviceName: "Pontiac",
    type: "Cable",
    busFrom: "Teal",
    busSectionFrom: "CMA",
    busTo: "ADF",
    busSectionTo: "LTCP",
    positiveSequenceRohmsperunitlength: 44,
    positiveSequenceXohmsperunitlength: 7,
    positiveSequenceBseimensperunitlength: 67,
    negativeSequenceRohmsperunitlength: 13,
    negativeSequenceXohmsperunitlength: 97,
    negativeSequenceBseimensperunitlength: 99,
    lengthKm: 85,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Aquamarine",
    busSectionFrom: "TRTN",
    busTo: "CTK",
    positiveSequenceRohmsperunitlength: 81,
    positiveSequenceXohmsperunitlength: 6,
    positiveSequenceBseimensperunitlength: 34,
    negativeSequenceRohmsperunitlength: 3,
    negativeSequenceXohmsperunitlength: 83,
    negativeSequenceBseimensperunitlength: 55,
    lengthKm: 33,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "China",
  },
  {
    deviceName: "Volkswagen",
    type: "Cable",
    busFrom: "Violet",
    busSectionFrom: "NWHM",
    busTo: "NAR",
    busSectionTo: "SKPN",
    positiveSequenceRohmsperunitlength: 66,
    positiveSequenceXohmsperunitlength: 77,
    positiveSequenceBseimensperunitlength: 11,
    negativeSequenceRohmsperunitlength: 55,
    negativeSequenceXohmsperunitlength: 11,
    negativeSequenceBseimensperunitlength: 81,
    lengthKm: 73,
    lineReactorFrom: "Granite",
    lineReactorTo: "Nigeria",
  },
  {
    deviceName: "Mazda",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "SOXX",
    busTo: "CGC",
    busSectionTo: "AYCG",
    positiveSequenceRohmsperunitlength: 43,
    positiveSequenceXohmsperunitlength: 79,
    positiveSequenceBseimensperunitlength: 33,
    negativeSequenceRohmsperunitlength: 28,
    negativeSequenceXohmsperunitlength: 68,
    negativeSequenceBseimensperunitlength: 31,
    lengthKm: 87,
    lineReactorFrom: "Brass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Dodge",
    type: "Over head conductor",
    busFrom: "Mauv",
    busSectionFrom: "GYC",
    busTo: "OER",
    busSectionTo: "ESNO",
    positiveSequenceRohmsperunitlength: 43,
    positiveSequenceXohmsperunitlength: 71,
    positiveSequenceBseimensperunitlength: 68,
    negativeSequenceRohmsperunitlength: 18,
    negativeSequenceXohmsperunitlength: 47,
    negativeSequenceBseimensperunitlength: 82,
    lengthKm: 51,
    lineReactorFrom: "Granite",
    lineReactorTo: "Brazil",
  },
  {
    deviceName: "Porsche",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "EBIO",
    busTo: "ERB",
    busSectionTo: "YERN",
    positiveSequenceRohmsperunitlength: 53,
    positiveSequenceXohmsperunitlength: 94,
    positiveSequenceBseimensperunitlength: 2,
    negativeSequenceRohmsperunitlength: 62,
    negativeSequenceXohmsperunitlength: 16,
    negativeSequenceBseimensperunitlength: 71,
    lengthKm: 82,
    lineReactorFrom: "Steel",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Porsche",
    type: "Cable",
    busFrom: "Orange",
    busSectionFrom: "CATO",
    busTo: "LNL",
    busSectionTo: "ZLLN",
    positiveSequenceRohmsperunitlength: 5,
    positiveSequenceXohmsperunitlength: 75,
    positiveSequenceBseimensperunitlength: 61,
    negativeSequenceRohmsperunitlength: 35,
    negativeSequenceXohmsperunitlength: 97,
    negativeSequenceBseimensperunitlength: 13,
    lengthKm: 11,
    lineReactorFrom: "Stone",
    lineReactorTo: "Portugal",
  },
  {
    deviceName: "Maserati",
    type: "Over head conductor",
    busFrom: "Green",
    busSectionFrom: "FTD",
    busTo: "JIQ",
    busSectionTo: "ZUQJ",
    positiveSequenceRohmsperunitlength: 41,
    positiveSequenceXohmsperunitlength: 57,
    positiveSequenceBseimensperunitlength: 2,
    negativeSequenceRohmsperunitlength: 15,
    negativeSequenceXohmsperunitlength: 18,
    negativeSequenceBseimensperunitlength: 76,
    lengthKm: 66,
    lineReactorFrom: "Brass",
    lineReactorTo: "United States",
  },
  {
    deviceName: "Cadillac",
    type: "Cable",
    busFrom: "Crimson",
    busSectionFrom: "KONE",
    busTo: "INX",
    busSectionTo: "WASI",
    positiveSequenceRohmsperunitlength: 46,
    positiveSequenceXohmsperunitlength: 14,
    positiveSequenceBseimensperunitlength: 65,
    negativeSequenceRohmsperunitlength: 68,
    negativeSequenceXohmsperunitlength: 43,
    negativeSequenceBseimensperunitlength: 77,
    lengthKm: 9,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Violet",
    busSectionFrom: "OLP",
    busTo: "DNO",
    busSectionTo: "SWDN",
    positiveSequenceRohmsperunitlength: 27,
    positiveSequenceXohmsperunitlength: 47,
    positiveSequenceBseimensperunitlength: 44,
    negativeSequenceRohmsperunitlength: 12,
    negativeSequenceXohmsperunitlength: 11,
    negativeSequenceBseimensperunitlength: 87,
    lengthKm: 25,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Iceland",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Goldenrod",
    busSectionFrom: "AMED",
    busTo: "CFR",
    busSectionTo: "LFRK",
    positiveSequenceRohmsperunitlength: 99,
    positiveSequenceXohmsperunitlength: 1,
    positiveSequenceBseimensperunitlength: 16,
    negativeSequenceRohmsperunitlength: 25,
    negativeSequenceXohmsperunitlength: 78,
    negativeSequenceBseimensperunitlength: 39,
    lengthKm: 71,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Volvo",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "MNOV",
    busTo: "TAC",
    busSectionTo: "RPVA",
    positiveSequenceRohmsperunitlength: 16,
    positiveSequenceXohmsperunitlength: 41,
    positiveSequenceBseimensperunitlength: 90,
    negativeSequenceRohmsperunitlength: 51,
    negativeSequenceXohmsperunitlength: 23,
    negativeSequenceBseimensperunitlength: 8,
    lengthKm: 20,
    lineReactorFrom: "Steel",
    lineReactorTo: "Serbia",
  },
  {
    deviceName: "Lincoln",
    type: "Cable",
    busFrom: "Red",
    busSectionFrom: "ACN",
    busTo: "TTB",
    busSectionTo: "LIET",
    positiveSequenceRohmsperunitlength: 55,
    positiveSequenceXohmsperunitlength: 43,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 86,
    negativeSequenceXohmsperunitlength: 33,
    negativeSequenceBseimensperunitlength: 56,
    lengthKm: 77,
    lineReactorFrom: "Aluminum",
    lineReactorTo: "Czech Republic",
  },
  {
    deviceName: "Aston Martin",
    type: "Cable",
    busFrom: "Yellow",
    busSectionFrom: "BIS",
    busTo: "TRY",
    busSectionTo: "HUTO",
    positiveSequenceRohmsperunitlength: 51,
    positiveSequenceXohmsperunitlength: 66,
    positiveSequenceBseimensperunitlength: 82,
    negativeSequenceRohmsperunitlength: 44,
    negativeSequenceXohmsperunitlength: 87,
    negativeSequenceBseimensperunitlength: 46,
    lengthKm: 76,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "Volvo",
    type: "Over head conductor",
    busFrom: "Aquamarine",
    busSectionFrom: "MBII",
    busTo: "HLS",
    busSectionTo: "YSTH",
    positiveSequenceRohmsperunitlength: 7,
    positiveSequenceXohmsperunitlength: 57,
    positiveSequenceBseimensperunitlength: 6,
    negativeSequenceRohmsperunitlength: 21,
    negativeSequenceXohmsperunitlength: 14,
    negativeSequenceBseimensperunitlength: 39,
    lengthKm: 54,
    lineReactorFrom: "Stone",
    lineReactorTo: "Argentina",
  },
  {
    deviceName: "Chrysler",
    type: "Over head conductor",
    busFrom: "Red",
    busSectionFrom: "MVIS",
    busTo: "PIZ",
    busSectionTo: "PPIZ",
    positiveSequenceRohmsperunitlength: 4,
    positiveSequenceXohmsperunitlength: 5,
    positiveSequenceBseimensperunitlength: 63,
    negativeSequenceRohmsperunitlength: 20,
    negativeSequenceXohmsperunitlength: 21,
    negativeSequenceBseimensperunitlength: 52,
    lengthKm: 93,
    lineReactorFrom: "Stone",
    lineReactorTo: "Australia",
  },
  {
    deviceName: "Ford",
    type: "Over head conductor",
    busFrom: "Blue",
    busSectionFrom: "XEC",
    busTo: "UNI",
    busSectionTo: "TVSU",
    positiveSequenceRohmsperunitlength: 45,
    positiveSequenceXohmsperunitlength: 87,
    positiveSequenceBseimensperunitlength: 62,
    negativeSequenceRohmsperunitlength: 68,
    negativeSequenceXohmsperunitlength: 3,
    negativeSequenceBseimensperunitlength: 58,
    lengthKm: 94,
    lineReactorFrom: "Glass",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Suzuki",
    type: "Cable",
    busFrom: "Aquamarine",
    busSectionFrom: "TSRO",
    busTo: "YEV",
    busSectionTo: "CYEV",
    positiveSequenceRohmsperunitlength: 33,
    positiveSequenceXohmsperunitlength: 90,
    positiveSequenceBseimensperunitlength: 8,
    negativeSequenceRohmsperunitlength: 10,
    negativeSequenceXohmsperunitlength: 70,
    negativeSequenceBseimensperunitlength: 24,
    lengthKm: 21,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Cambodia",
  },
  {
    deviceName: "Spyker",
    type: "Cable",
    busFrom: "Yellow",
    busSectionFrom: "AEY",
    busTo: "CFM",
    busSectionTo: "CET2",
    positiveSequenceRohmsperunitlength: 73,
    positiveSequenceXohmsperunitlength: 41,
    positiveSequenceBseimensperunitlength: 13,
    negativeSequenceRohmsperunitlength: 63,
    negativeSequenceXohmsperunitlength: 85,
    negativeSequenceBseimensperunitlength: 24,
    lengthKm: 79,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "China",
  },
  {
    deviceName: "Volkswagen",
    type: "Cable",
    busFrom: "Puce",
    busSectionFrom: "CIF",
    busTo: "DEX",
    busSectionTo: "WAVD",
    positiveSequenceRohmsperunitlength: 7,
    positiveSequenceXohmsperunitlength: 73,
    positiveSequenceBseimensperunitlength: 72,
    negativeSequenceRohmsperunitlength: 10,
    negativeSequenceXohmsperunitlength: 54,
    negativeSequenceBseimensperunitlength: 20,
    lengthKm: 87,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Peru",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Cable",
    busFrom: "Pink",
    busSectionFrom: "KNSL",
    busTo: "KCB",
    busSectionTo: "SMTP",
    positiveSequenceRohmsperunitlength: 27,
    positiveSequenceXohmsperunitlength: 54,
    positiveSequenceBseimensperunitlength: 40,
    negativeSequenceRohmsperunitlength: 86,
    negativeSequenceXohmsperunitlength: 7,
    negativeSequenceBseimensperunitlength: 99,
    lengthKm: 2,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Japan",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Green",
    busSectionFrom: "GOGO",
    busTo: "MQJ",
    busSectionTo: "UEMA",
    positiveSequenceRohmsperunitlength: 61,
    positiveSequenceXohmsperunitlength: 96,
    positiveSequenceBseimensperunitlength: 4,
    negativeSequenceRohmsperunitlength: 97,
    negativeSequenceXohmsperunitlength: 99,
    negativeSequenceBseimensperunitlength: 1,
    lengthKm: 19,
    lineReactorFrom: "Wood",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Mercedes-Benz",
    type: "Over head conductor",
    busFrom: "Maroon",
    busSectionFrom: "SRNE",
    busTo: "DLC",
    busSectionTo: "ZYTL",
    positiveSequenceRohmsperunitlength: 10,
    positiveSequenceXohmsperunitlength: 55,
    positiveSequenceBseimensperunitlength: 81,
    negativeSequenceRohmsperunitlength: 28,
    negativeSequenceXohmsperunitlength: 41,
    negativeSequenceBseimensperunitlength: 66,
    lengthKm: 96,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Russia",
  },
  {
    deviceName: "Pontiac",
    type: "Cable",
    busFrom: "Mauv",
    busSectionFrom: "PSAU",
    busTo: "LPT",
    busSectionTo: "VTCL",
    positiveSequenceRohmsperunitlength: 91,
    positiveSequenceXohmsperunitlength: 63,
    positiveSequenceBseimensperunitlength: 85,
    negativeSequenceRohmsperunitlength: 41,
    negativeSequenceXohmsperunitlength: 31,
    negativeSequenceBseimensperunitlength: 82,
    lengthKm: 37,
    lineReactorFrom: "Vinyl",
    lineReactorTo: "Netherlands",
  },
  {
    deviceName: "Toyota",
    type: "Over head conductor",
    busFrom: "Yellow",
    busSectionFrom: "BIF",
    busTo: "TUG",
    busSectionTo: "RPUT",
    positiveSequenceRohmsperunitlength: 25,
    positiveSequenceXohmsperunitlength: 9,
    positiveSequenceBseimensperunitlength: 7,
    negativeSequenceRohmsperunitlength: 26,
    negativeSequenceXohmsperunitlength: 97,
    negativeSequenceBseimensperunitlength: 95,
    lengthKm: 1,
    lineReactorFrom: "Glass",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Chevrolet",
    type: "Cable",
    busFrom: "Pink",
    busSectionFrom: "MS^K",
    busTo: "TYR",
    busSectionTo: "KTYR",
    positiveSequenceRohmsperunitlength: 16,
    positiveSequenceXohmsperunitlength: 83,
    positiveSequenceBseimensperunitlength: 22,
    negativeSequenceRohmsperunitlength: 23,
    negativeSequenceXohmsperunitlength: 36,
    negativeSequenceBseimensperunitlength: 58,
    lengthKm: 33,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Spain",
  },
  {
    deviceName: "Infiniti",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "DFT",
    busTo: "YBI",
    busSectionTo: "CCE4",
    positiveSequenceRohmsperunitlength: 76,
    positiveSequenceXohmsperunitlength: 18,
    positiveSequenceBseimensperunitlength: 70,
    negativeSequenceRohmsperunitlength: 66,
    negativeSequenceXohmsperunitlength: 87,
    negativeSequenceBseimensperunitlength: 48,
    lengthKm: 13,
    lineReactorFrom: "Plexiglass",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Nissan",
    type: "Over head conductor",
    busFrom: "Mauv",
    busSectionFrom: "SBPH",
    busTo: "PZB",
    busSectionTo: "FAPM",
    positiveSequenceRohmsperunitlength: 83,
    positiveSequenceXohmsperunitlength: 26,
    positiveSequenceBseimensperunitlength: 36,
    negativeSequenceRohmsperunitlength: 40,
    negativeSequenceXohmsperunitlength: 55,
    negativeSequenceBseimensperunitlength: 59,
    lengthKm: 81,
    lineReactorFrom: "Rubber",
    lineReactorTo: "Sweden",
  },
  {
    deviceName: "Pontiac",
    type: "Cable",
    busFrom: "Purple",
    busSectionFrom: "UHAL",
    busTo: "STK",
    busSectionTo: "KSTK",
    positiveSequenceRohmsperunitlength: 37,
    positiveSequenceXohmsperunitlength: 34,
    positiveSequenceBseimensperunitlength: 61,
    negativeSequenceRohmsperunitlength: 91,
    negativeSequenceXohmsperunitlength: 93,
    negativeSequenceBseimensperunitlength: 42,
    lengthKm: 7,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Philippines",
  },
  {
    deviceName: "Cadillac",
    type: "Cable",
    busFrom: "Mauv",
    busSectionFrom: "CORI",
    busTo: "OPW",
    busSectionTo: "FYOP",
    positiveSequenceRohmsperunitlength: 34,
    positiveSequenceXohmsperunitlength: 18,
    positiveSequenceBseimensperunitlength: 23,
    negativeSequenceRohmsperunitlength: 54,
    negativeSequenceXohmsperunitlength: 95,
    negativeSequenceBseimensperunitlength: 25,
    lengthKm: 28,
    lineReactorFrom: "Granite",
    lineReactorTo: "Indonesia",
  },
  {
    deviceName: "Chevrolet",
    type: "Over head conductor",
    busFrom: "Violet",
    busSectionFrom: "ALL^C",
    busTo: "TLX",
    busSectionTo: "SCTL",
    positiveSequenceRohmsperunitlength: 30,
    positiveSequenceXohmsperunitlength: 48,
    positiveSequenceBseimensperunitlength: 55,
    negativeSequenceRohmsperunitlength: 29,
    negativeSequenceXohmsperunitlength: 84,
    negativeSequenceBseimensperunitlength: 96,
    lengthKm: 19,
    lineReactorFrom: "Steel",
    lineReactorTo: "Slovenia",
  },
  {
    deviceName: "GMC",
    type: "Cable",
    busFrom: "Fuscia",
    busSectionFrom: "PCI",
    busTo: "LUV",
    busSectionTo: "WAPL",
    positiveSequenceRohmsperunitlength: 98,
    positiveSequenceXohmsperunitlength: 92,
    positiveSequenceBseimensperunitlength: 81,
    negativeSequenceRohmsperunitlength: 20,
    negativeSequenceXohmsperunitlength: 6,
    negativeSequenceBseimensperunitlength: 27,
    lengthKm: 50,
    lineReactorFrom: "Granite",
    lineReactorTo: "China",
  },
  {
    deviceName: "Cadillac",
    type: "Over head conductor",
    busFrom: "Purple",
    busSectionFrom: "RGT",
    busTo: "XXN",
    busSectionTo: "OERY",
    positiveSequenceRohmsperunitlength: 29,
    positiveSequenceXohmsperunitlength: 92,
    positiveSequenceBseimensperunitlength: 47,
    negativeSequenceRohmsperunitlength: 99,
    negativeSequenceXohmsperunitlength: 41,
    negativeSequenceBseimensperunitlength: 81,
    lengthKm: 86,
    lineReactorFrom: "Plastic",
    lineReactorTo: "Poland",
  },
  {
    deviceName: "GMC",
    type: "Cable",
    busFrom: "Yellow",
    busSectionFrom: "AFSS",
    busTo: "GUJ",
    busSectionTo: "SBGW",
    positiveSequenceRohmsperunitlength: 49,
    positiveSequenceXohmsperunitlength: 59,
    positiveSequenceBseimensperunitlength: 40,
    negativeSequenceRohmsperunitlength: 91,
    negativeSequenceXohmsperunitlength: 51,
    negativeSequenceBseimensperunitlength: 24,
    lengthKm: 8,
    lineReactorFrom: "Stone",
    lineReactorTo: "Laos",
  },
];

const page = async () => {
  const session = await getServerSession(authOptions);
  const { data: columns } = await getDefaultParams();

  return (
    <PushMockData
      mockData={mockData}
      session={session}
      columns={columns[0].transmissionLinesColumns}
    />
  );
};

export default page;
