import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import SessionProvider from "@/context/AuthContext";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import { authOptions } from "../api/auth/[...nextauth]/route";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="flex">
        <SessionProvider session={session}>
          <NextTopLoader />
          <Sidebar />
          <div className="p-3 pt-10 pl-10 w-screen h-screen overflow-auto">{children}</div>
          <Navbar />
        </SessionProvider>
      </body>
      <Toaster
        position="top-center"
        richColors
        closeButton={true}
        duration={4000}
      />
    </html>
  );
}
