import { Toaster } from "sonner";
import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import NextTopLoader from "nextjs-toploader";
import NavigationMenubar from "@/components/ui/NavigationMenubar/NavigationMenubar";
import ToasterContext from "@/context/ToasterContext";
import SessionProvider from "@/context/AuthContext";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body className="flex">
      <SessionProvider session={session}>
          
        <NextTopLoader />
        <Sidebar />
        <div className="p-3 pt-10 pl-10 w-screen h-screen overflow-auto">{children}</div>
        <ToasterContext />
        </SessionProvider>
      </body>
      <Toaster
        position="top-center"
        richColors
      />
    </html>
  );
}
